/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppZatcaRouteImport } from './routes/_app.zatca'
import { Route as AppWarehousesRouteImport } from './routes/_app.warehouses'
import { Route as AppWarehouseSuppliersRouteImport } from './routes/_app.warehouse-suppliers'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTerminalsRouteImport } from './routes/_app.terminals'
import { Route as AppTerminalSessionsRouteImport } from './routes/_app.terminal-sessions'
import { Route as AppTaxReportsRouteImport } from './routes/_app.tax-reports'
import { Route as AppTaxFeesRouteImport } from './routes/_app.tax-fees'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppStocksRouteImport } from './routes/_app.stocks'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppReturnsRouteImport } from './routes/_app.returns'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRefundsRouteImport } from './routes/_app.refunds'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppPosSettingsRouteImport } from './routes/_app.pos-settings'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppPlansRouteImport } from './routes/_app.plans'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppMposAppRouteImport } from './routes/_app.mpos-app'
import { Route as AppMobilePosRouteImport } from './routes/_app.mobile-pos'
import { Route as AppMartSuppliersRouteImport } from './routes/_app.mart-suppliers'
import { Route as AppMaintenanceRouteImport } from './routes/_app.maintenance'
import { Route as AppKpiRouteImport } from './routes/_app.kpi'
import { Route as AppKioskRouteImport } from './routes/_app.kiosk'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppExpenseTypesRouteImport } from './routes/_app.expense-types'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDeviceBehaviorRouteImport } from './routes/_app.device-behavior'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCouponsRouteImport } from './routes/_app.coupons'
import { Route as AppControlTowerRouteImport } from './routes/_app.control-tower'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppCashierShiftRouteImport } from './routes/_app.cashier-shift'
import { Route as AppCashierRouteImport } from './routes/_app.cashier'
import { Route as AppBranchesRouteImport } from './routes/_app.branches'
import { Route as AppBiRouteImport } from './routes/_app.bi'
import { Route as AppBatchesRouteImport } from './routes/_app.batches'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppControlTowerBranchIdRouteImport } from './routes/_app.control-tower.$branchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZatcaRoute = AppZatcaRouteImport.update({
  id: '/zatca',
  path: '/zatca',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehouseSuppliersRoute = AppWarehouseSuppliersRouteImport.update({
  id: '/warehouse-suppliers',
  path: '/warehouse-suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalsRoute = AppTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalSessionsRoute = AppTerminalSessionsRouteImport.update({
  id: '/terminal-sessions',
  path: '/terminal-sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxReportsRoute = AppTaxReportsRouteImport.update({
  id: '/tax-reports',
  path: '/tax-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxFeesRoute = AppTaxFeesRouteImport.update({
  id: '/tax-fees',
  path: '/tax-fees',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStocksRoute = AppStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRefundsRoute = AppRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPosSettingsRoute = AppPosSettingsRouteImport.update({
  id: '/pos-settings',
  path: '/pos-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMposAppRoute = AppMposAppRouteImport.update({
  id: '/mpos-app',
  path: '/mpos-app',
  getParentRoute: () => AppRoute,
} as any)
const AppMobilePosRoute = AppMobilePosRouteImport.update({
  id: '/mobile-pos',
  path: '/mobile-pos',
  getParentRoute: () => AppRoute,
} as any)
const AppMartSuppliersRoute = AppMartSuppliersRouteImport.update({
  id: '/mart-suppliers',
  path: '/mart-suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceRoute = AppMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AppRoute,
} as any)
const AppKpiRoute = AppKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AppRoute,
} as any)
const AppKioskRoute = AppKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseTypesRoute = AppExpenseTypesRouteImport.update({
  id: '/expense-types',
  path: '/expense-types',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDeviceBehaviorRoute = AppDeviceBehaviorRouteImport.update({
  id: '/device-behavior',
  path: '/device-behavior',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCouponsRoute = AppCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AppRoute,
} as any)
const AppControlTowerRoute = AppControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierShiftRoute = AppCashierShiftRouteImport.update({
  id: '/cashier-shift',
  path: '/cashier-shift',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierRoute = AppCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppBiRoute = AppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesRoute = AppBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppControlTowerBranchIdRoute = AppControlTowerBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => AppControlTowerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/batches': typeof AppBatchesRoute
  '/bi': typeof AppBiRoute
  '/branches': typeof AppBranchesRoute
  '/cashier': typeof AppCashierRoute
  '/cashier-shift': typeof AppCashierShiftRoute
  '/compliance': typeof AppComplianceRoute
  '/control-tower': typeof AppControlTowerRouteWithChildren
  '/coupons': typeof AppCouponsRoute
  '/dashboard': typeof AppDashboardRoute
  '/device-behavior': typeof AppDeviceBehaviorRoute
  '/devices': typeof AppDevicesRoute
  '/expense-types': typeof AppExpenseTypesRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/kiosk': typeof AppKioskRoute
  '/kpi': typeof AppKpiRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/mart-suppliers': typeof AppMartSuppliersRoute
  '/mobile-pos': typeof AppMobilePosRoute
  '/mpos-app': typeof AppMposAppRoute
  '/orders': typeof AppOrdersRoute
  '/plans': typeof AppPlansRoute
  '/pos': typeof AppPosRoute
  '/pos-settings': typeof AppPosSettingsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/refunds': typeof AppRefundsRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/roles': typeof AppRolesRoute
  '/rules': typeof AppRulesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/stocks': typeof AppStocksRoute
  '/suppliers': typeof AppSuppliersRoute
  '/tax-fees': typeof AppTaxFeesRoute
  '/tax-reports': typeof AppTaxReportsRoute
  '/terminal-sessions': typeof AppTerminalSessionsRoute
  '/terminals': typeof AppTerminalsRoute
  '/users': typeof AppUsersRoute
  '/warehouse-suppliers': typeof AppWarehouseSuppliersRoute
  '/warehouses': typeof AppWarehousesRoute
  '/zatca': typeof AppZatcaRoute
  '/control-tower/$branchId': typeof AppControlTowerBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/batches': typeof AppBatchesRoute
  '/bi': typeof AppBiRoute
  '/branches': typeof AppBranchesRoute
  '/cashier': typeof AppCashierRoute
  '/cashier-shift': typeof AppCashierShiftRoute
  '/compliance': typeof AppComplianceRoute
  '/control-tower': typeof AppControlTowerRouteWithChildren
  '/coupons': typeof AppCouponsRoute
  '/dashboard': typeof AppDashboardRoute
  '/device-behavior': typeof AppDeviceBehaviorRoute
  '/devices': typeof AppDevicesRoute
  '/expense-types': typeof AppExpenseTypesRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/kiosk': typeof AppKioskRoute
  '/kpi': typeof AppKpiRoute
  '/maintenance': typeof AppMaintenanceRoute
  '/mart-suppliers': typeof AppMartSuppliersRoute
  '/mobile-pos': typeof AppMobilePosRoute
  '/mpos-app': typeof AppMposAppRoute
  '/orders': typeof AppOrdersRoute
  '/plans': typeof AppPlansRoute
  '/pos': typeof AppPosRoute
  '/pos-settings': typeof AppPosSettingsRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/refunds': typeof AppRefundsRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/roles': typeof AppRolesRoute
  '/rules': typeof AppRulesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/stocks': typeof AppStocksRoute
  '/suppliers': typeof AppSuppliersRoute
  '/tax-fees': typeof AppTaxFeesRoute
  '/tax-reports': typeof AppTaxReportsRoute
  '/terminal-sessions': typeof AppTerminalSessionsRoute
  '/terminals': typeof AppTerminalsRoute
  '/users': typeof AppUsersRoute
  '/warehouse-suppliers': typeof AppWarehouseSuppliersRoute
  '/warehouses': typeof AppWarehousesRoute
  '/zatca': typeof AppZatcaRoute
  '/control-tower/$branchId': typeof AppControlTowerBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/batches': typeof AppBatchesRoute
  '/_app/bi': typeof AppBiRoute
  '/_app/branches': typeof AppBranchesRoute
  '/_app/cashier': typeof AppCashierRoute
  '/_app/cashier-shift': typeof AppCashierShiftRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/control-tower': typeof AppControlTowerRouteWithChildren
  '/_app/coupons': typeof AppCouponsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/device-behavior': typeof AppDeviceBehaviorRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/expense-types': typeof AppExpenseTypesRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/kiosk': typeof AppKioskRoute
  '/_app/kpi': typeof AppKpiRoute
  '/_app/maintenance': typeof AppMaintenanceRoute
  '/_app/mart-suppliers': typeof AppMartSuppliersRoute
  '/_app/mobile-pos': typeof AppMobilePosRoute
  '/_app/mpos-app': typeof AppMposAppRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/pos-settings': typeof AppPosSettingsRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/refunds': typeof AppRefundsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/stocks': typeof AppStocksRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/tax-fees': typeof AppTaxFeesRoute
  '/_app/tax-reports': typeof AppTaxReportsRoute
  '/_app/terminal-sessions': typeof AppTerminalSessionsRoute
  '/_app/terminals': typeof AppTerminalsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/warehouse-suppliers': typeof AppWarehouseSuppliersRoute
  '/_app/warehouses': typeof AppWarehousesRoute
  '/_app/zatca': typeof AppZatcaRoute
  '/_app/control-tower/$branchId': typeof AppControlTowerBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/audit-logs'
    | '/batches'
    | '/bi'
    | '/branches'
    | '/cashier'
    | '/cashier-shift'
    | '/compliance'
    | '/control-tower'
    | '/coupons'
    | '/dashboard'
    | '/device-behavior'
    | '/devices'
    | '/expense-types'
    | '/expenses'
    | '/inventory'
    | '/kiosk'
    | '/kpi'
    | '/maintenance'
    | '/mart-suppliers'
    | '/mobile-pos'
    | '/mpos-app'
    | '/orders'
    | '/plans'
    | '/pos'
    | '/pos-settings'
    | '/purchase-orders'
    | '/refunds'
    | '/reports'
    | '/returns'
    | '/roles'
    | '/rules'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/stocks'
    | '/suppliers'
    | '/tax-fees'
    | '/tax-reports'
    | '/terminal-sessions'
    | '/terminals'
    | '/users'
    | '/warehouse-suppliers'
    | '/warehouses'
    | '/zatca'
    | '/control-tower/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/audit-logs'
    | '/batches'
    | '/bi'
    | '/branches'
    | '/cashier'
    | '/cashier-shift'
    | '/compliance'
    | '/control-tower'
    | '/coupons'
    | '/dashboard'
    | '/device-behavior'
    | '/devices'
    | '/expense-types'
    | '/expenses'
    | '/inventory'
    | '/kiosk'
    | '/kpi'
    | '/maintenance'
    | '/mart-suppliers'
    | '/mobile-pos'
    | '/mpos-app'
    | '/orders'
    | '/plans'
    | '/pos'
    | '/pos-settings'
    | '/purchase-orders'
    | '/refunds'
    | '/reports'
    | '/returns'
    | '/roles'
    | '/rules'
    | '/sales'
    | '/settings'
    | '/staff'
    | '/stocks'
    | '/suppliers'
    | '/tax-fees'
    | '/tax-reports'
    | '/terminal-sessions'
    | '/terminals'
    | '/users'
    | '/warehouse-suppliers'
    | '/warehouses'
    | '/zatca'
    | '/control-tower/$branchId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/audit-logs'
    | '/_app/batches'
    | '/_app/bi'
    | '/_app/branches'
    | '/_app/cashier'
    | '/_app/cashier-shift'
    | '/_app/compliance'
    | '/_app/control-tower'
    | '/_app/coupons'
    | '/_app/dashboard'
    | '/_app/device-behavior'
    | '/_app/devices'
    | '/_app/expense-types'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/kiosk'
    | '/_app/kpi'
    | '/_app/maintenance'
    | '/_app/mart-suppliers'
    | '/_app/mobile-pos'
    | '/_app/mpos-app'
    | '/_app/orders'
    | '/_app/plans'
    | '/_app/pos'
    | '/_app/pos-settings'
    | '/_app/purchase-orders'
    | '/_app/refunds'
    | '/_app/reports'
    | '/_app/returns'
    | '/_app/roles'
    | '/_app/rules'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/stocks'
    | '/_app/suppliers'
    | '/_app/tax-fees'
    | '/_app/tax-reports'
    | '/_app/terminal-sessions'
    | '/_app/terminals'
    | '/_app/users'
    | '/_app/warehouse-suppliers'
    | '/_app/warehouses'
    | '/_app/zatca'
    | '/_app/control-tower/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zatca': {
      id: '/_app/zatca'
      path: '/zatca'
      fullPath: '/zatca'
      preLoaderRoute: typeof AppZatcaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses': {
      id: '/_app/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouse-suppliers': {
      id: '/_app/warehouse-suppliers'
      path: '/warehouse-suppliers'
      fullPath: '/warehouse-suppliers'
      preLoaderRoute: typeof AppWarehouseSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminals': {
      id: '/_app/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof AppTerminalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terminal-sessions': {
      id: '/_app/terminal-sessions'
      path: '/terminal-sessions'
      fullPath: '/terminal-sessions'
      preLoaderRoute: typeof AppTerminalSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax-reports': {
      id: '/_app/tax-reports'
      path: '/tax-reports'
      fullPath: '/tax-reports'
      preLoaderRoute: typeof AppTaxReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax-fees': {
      id: '/_app/tax-fees'
      path: '/tax-fees'
      fullPath: '/tax-fees'
      preLoaderRoute: typeof AppTaxFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stocks': {
      id: '/_app/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AppStocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refunds': {
      id: '/_app/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof AppRefundsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos-settings': {
      id: '/_app/pos-settings'
      path: '/pos-settings'
      fullPath: '/pos-settings'
      preLoaderRoute: typeof AppPosSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mpos-app': {
      id: '/_app/mpos-app'
      path: '/mpos-app'
      fullPath: '/mpos-app'
      preLoaderRoute: typeof AppMposAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile-pos': {
      id: '/_app/mobile-pos'
      path: '/mobile-pos'
      fullPath: '/mobile-pos'
      preLoaderRoute: typeof AppMobilePosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mart-suppliers': {
      id: '/_app/mart-suppliers'
      path: '/mart-suppliers'
      fullPath: '/mart-suppliers'
      preLoaderRoute: typeof AppMartSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance': {
      id: '/_app/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AppMaintenanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kpi': {
      id: '/_app/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AppKpiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kiosk': {
      id: '/_app/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof AppKioskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense-types': {
      id: '/_app/expense-types'
      path: '/expense-types'
      fullPath: '/expense-types'
      preLoaderRoute: typeof AppExpenseTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/device-behavior': {
      id: '/_app/device-behavior'
      path: '/device-behavior'
      fullPath: '/device-behavior'
      preLoaderRoute: typeof AppDeviceBehaviorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coupons': {
      id: '/_app/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AppCouponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-tower': {
      id: '/_app/control-tower'
      path: '/control-tower'
      fullPath: '/control-tower'
      preLoaderRoute: typeof AppControlTowerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier-shift': {
      id: '/_app/cashier-shift'
      path: '/cashier-shift'
      fullPath: '/cashier-shift'
      preLoaderRoute: typeof AppCashierShiftRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier': {
      id: '/_app/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AppCashierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches': {
      id: '/_app/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bi': {
      id: '/_app/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AppBiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/batches': {
      id: '/_app/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AppBatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-tower/$branchId': {
      id: '/_app/control-tower/$branchId'
      path: '/$branchId'
      fullPath: '/control-tower/$branchId'
      preLoaderRoute: typeof AppControlTowerBranchIdRouteImport
      parentRoute: typeof AppControlTowerRoute
    }
  }
}

interface AppControlTowerRouteChildren {
  AppControlTowerBranchIdRoute: typeof AppControlTowerBranchIdRoute
}

const AppControlTowerRouteChildren: AppControlTowerRouteChildren = {
  AppControlTowerBranchIdRoute: AppControlTowerBranchIdRoute,
}

const AppControlTowerRouteWithChildren = AppControlTowerRoute._addFileChildren(
  AppControlTowerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppBatchesRoute: typeof AppBatchesRoute
  AppBiRoute: typeof AppBiRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCashierRoute: typeof AppCashierRoute
  AppCashierShiftRoute: typeof AppCashierShiftRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppControlTowerRoute: typeof AppControlTowerRouteWithChildren
  AppCouponsRoute: typeof AppCouponsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeviceBehaviorRoute: typeof AppDeviceBehaviorRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppExpenseTypesRoute: typeof AppExpenseTypesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppKioskRoute: typeof AppKioskRoute
  AppKpiRoute: typeof AppKpiRoute
  AppMaintenanceRoute: typeof AppMaintenanceRoute
  AppMartSuppliersRoute: typeof AppMartSuppliersRoute
  AppMobilePosRoute: typeof AppMobilePosRoute
  AppMposAppRoute: typeof AppMposAppRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPlansRoute: typeof AppPlansRoute
  AppPosRoute: typeof AppPosRoute
  AppPosSettingsRoute: typeof AppPosSettingsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRefundsRoute: typeof AppRefundsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStocksRoute: typeof AppStocksRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTaxFeesRoute: typeof AppTaxFeesRoute
  AppTaxReportsRoute: typeof AppTaxReportsRoute
  AppTerminalSessionsRoute: typeof AppTerminalSessionsRoute
  AppTerminalsRoute: typeof AppTerminalsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWarehouseSuppliersRoute: typeof AppWarehouseSuppliersRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppZatcaRoute: typeof AppZatcaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppBatchesRoute: AppBatchesRoute,
  AppBiRoute: AppBiRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCashierRoute: AppCashierRoute,
  AppCashierShiftRoute: AppCashierShiftRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppControlTowerRoute: AppControlTowerRouteWithChildren,
  AppCouponsRoute: AppCouponsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeviceBehaviorRoute: AppDeviceBehaviorRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppExpenseTypesRoute: AppExpenseTypesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppKioskRoute: AppKioskRoute,
  AppKpiRoute: AppKpiRoute,
  AppMaintenanceRoute: AppMaintenanceRoute,
  AppMartSuppliersRoute: AppMartSuppliersRoute,
  AppMobilePosRoute: AppMobilePosRoute,
  AppMposAppRoute: AppMposAppRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPlansRoute: AppPlansRoute,
  AppPosRoute: AppPosRoute,
  AppPosSettingsRoute: AppPosSettingsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRefundsRoute: AppRefundsRoute,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppRolesRoute: AppRolesRoute,
  AppRulesRoute: AppRulesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppStocksRoute: AppStocksRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTaxFeesRoute: AppTaxFeesRoute,
  AppTaxReportsRoute: AppTaxReportsRoute,
  AppTerminalSessionsRoute: AppTerminalSessionsRoute,
  AppTerminalsRoute: AppTerminalsRoute,
  AppUsersRoute: AppUsersRoute,
  AppWarehouseSuppliersRoute: AppWarehouseSuppliersRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppZatcaRoute: AppZatcaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
